### ISSUE TITLE
Open Camera function not working as intented

### ISSUE THREAD

**Issue by LeoPTY** [snsurajnath/FunGallery#1]
Cloned the repo, tried to use the app but couldnt
[FunGallery-master.zip](https://github.com/snsurajnath/FunGallery/files/6819105/FunGallery-master.zip)

https://user-images.githubusercontent.com/40049372/125697790-a8f716c4-f5f1-4a61-a448-7692f85fc5ef.mp4

**Comment by snsurajnath** [comment]
In API level 29 https://github.com/snsurajnath/FunGallery/blob/6909881f2661bf061ada68bc0ee656c404c2076c/app/src/main/java/com/example/fungallery/MainActivity.java#L346
    `    File storageDirectory = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_PICTURES);`
is deprecated so new file not creating while you trying to open camera, that's why camera not opening when you clicked open camera button.
So, instead of calling  `    File storageDirectory = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_PICTURES);`
use `File storageDirectory = getExternalFilesDir(Environment.DIRECTORY_PICTURES);`
which is a private folder found in Android/data/com.example.fungallery/files/Pictures
